//..model/Modifier.java, uly, june2013..
package org.aschyiel.peaches.model;

/**
* Modifiers are generated by selecting moves during a turn;
* they alter game-object properties at the very end of the turn.
* Think of them as rows in a spreadsheet doing additions/subtractions to hp, etc.
*
* For Example:
* Losing life, gaining life, gaining speed, picking up an item, etc.
* are all captured via modifiers.
*/
public abstract class Modifier
{
  /** The default health diff. */
  protected int hp = 0;
}